package kyle.leis.eo.operation.predictwaybill.ebay.vo.response;
 
/**
 * Generated by FreeMarker
 *
 */
public class Buyer  
{
    /********** attribute ***********/
    private String Email;

    private String UserFirstName;

    private String UserLastName;

  
    /********** get/set ***********/
    public String getEmail() {
        return Email;
    }
 
    public void setEmail(String Email) {
        this.Email = Email;
    }

    public String getUserFirstName() {
        return UserFirstName;
    }
 
    public void setUserFirstName(String UserFirstName) {
        this.UserFirstName = UserFirstName;
    }

    public String getUserLastName() {
        return UserLastName;
    }
 
    public void setUserLastName(String UserLastName) {
        this.UserLastName = UserLastName;
    }

  
}