package kyle.leis.eo.operation.predictwaybill.ebay.vo.response;
 
/**
 * Generated by FreeMarker
 *
 */
public class CheckoutStatus  
{
    /********** attribute ***********/
    private String LastModifiedTime;

    private String Status;

  
    /********** get/set ***********/
    public String getLastModifiedTime() {
        return LastModifiedTime;
    }
 
    public void setLastModifiedTime(String LastModifiedTime) {
        this.LastModifiedTime = LastModifiedTime;
    }

    public String getStatus() {
        return Status;
    }
 
    public void setStatus(String Status) {
        this.Status = Status;
    }

  
}