package kyle.leis.eo.operation.predictwaybill.ebay.vo.response;
 
/**
 * Generated by FreeMarker
 *
 */
public class Item  
{
    /********** attribute ***********/
    private String ItemID;

    private String Site;

    private String Title;

    private String ConditionDisplayName;

  
    /********** get/set ***********/
    public String getItemID() {
        return ItemID;
    }
 
    public void setItemID(String ItemID) {
        this.ItemID = ItemID;
    }

    public String getSite() {
        return Site;
    }
 
    public void setSite(String Site) {
        this.Site = Site;
    }

    public String getTitle() {
        return Title;
    }
 
    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getConditionDisplayName() {
        return ConditionDisplayName;
    }
 
    public void setConditionDisplayName(String ConditionDisplayName) {
        this.ConditionDisplayName = ConditionDisplayName;
    }

  
}