package kyle.leis.eo.operation.predictwaybill.ebay.vo.response;

import java.util.List;
 
/**
 * Generated by FreeMarker
 *
 */
public class Order  
{
    /********** attribute ***********/
    private String OrderID;

    private String OrderStatus;

    private CheckoutStatus CheckoutStatus;

    private String CreatedTime;

    private String SellerEmail;

    private ShippingAddress ShippingAddress;

    private ShippingServiceSelected ShippingServiceSelected;

    private Subtotal Subtotal;

    private Total Total;

    private List<Transaction> TransactionArray;

    private String BuyerUserID;

    private String SellerUserID;

  
    /********** get/set ***********/
    public String getOrderID() {
        return OrderID;
    }
 
    public void setOrderID(String OrderID) {
        this.OrderID = OrderID;
    }

    public String getOrderStatus() {
        return OrderStatus;
    }
 
    public void setOrderStatus(String OrderStatus) {
        this.OrderStatus = OrderStatus;
    }

    public CheckoutStatus getCheckoutStatus() {
        return CheckoutStatus;
    }
 
    public void setCheckoutStatus(CheckoutStatus CheckoutStatus) {
        this.CheckoutStatus = CheckoutStatus;
    }

    public String getCreatedTime() {
        return CreatedTime;
    }
 
    public void setCreatedTime(String CreatedTime) {
        this.CreatedTime = CreatedTime;
    }

    public String getSellerEmail() {
        return SellerEmail;
    }
 
    public void setSellerEmail(String SellerEmail) {
        this.SellerEmail = SellerEmail;
    }

    public ShippingAddress getShippingAddress() {
        return ShippingAddress;
    }
 
    public void setShippingAddress(ShippingAddress ShippingAddress) {
        this.ShippingAddress = ShippingAddress;
    }

    public ShippingServiceSelected getShippingServiceSelected() {
        return ShippingServiceSelected;
    }
 
    public void setShippingServiceSelected(ShippingServiceSelected ShippingServiceSelected) {
        this.ShippingServiceSelected = ShippingServiceSelected;
    }

    public Subtotal getSubtotal() {
        return Subtotal;
    }
 
    public void setSubtotal(Subtotal Subtotal) {
        this.Subtotal = Subtotal;
    }

    public Total getTotal() {
        return Total;
    }
 
    public void setTotal(Total Total) {
        this.Total = Total;
    }

    public List<Transaction> getTransactionArray() {
        return TransactionArray;
    }
 
    public void setTransactionArray(List<Transaction> TransactionArray) {
        this.TransactionArray = TransactionArray;
    }

    public String getBuyerUserID() {
        return BuyerUserID;
    }
 
    public void setBuyerUserID(String BuyerUserID) {
        this.BuyerUserID = BuyerUserID;
    }

    public String getSellerUserID() {
        return SellerUserID;
    }
 
    public void setSellerUserID(String SellerUserID) {
        this.SellerUserID = SellerUserID;
    }

  
}