package kyle.leis.eo.operation.predictwaybill.ebay.vo.response;
 
/**
 * Generated by FreeMarker
 *
 */
public class PaginationResult  
{
    /********** attribute ***********/
    private int TotalNumberOfPages;

    private int TotalNumberOfEntries;

  
    /********** get/set ***********/
    public int getTotalNumberOfPages() {
        return TotalNumberOfPages;
    }
 
    public void setTotalNumberOfPages(int TotalNumberOfPages) {
        this.TotalNumberOfPages = TotalNumberOfPages;
    }

    public int getTotalNumberOfEntries() {
        return TotalNumberOfEntries;
    }
 
    public void setTotalNumberOfEntries(int TotalNumberOfEntries) {
        this.TotalNumberOfEntries = TotalNumberOfEntries;
    }

  
}