package kyle.leis.eo.operation.predictwaybill.ebay.vo.response;
 
/**
 * Generated by FreeMarker
 *
 */
public class ShippingServiceSelected  
{
    /********** attribute ***********/
    private String ShippingService;

    private ShippingServiceCost ShippingServiceCost;

  
    /********** get/set ***********/
    public String getShippingService() {
        return ShippingService;
    }
 
    public void setShippingService(String ShippingService) {
        this.ShippingService = ShippingService;
    }

    public ShippingServiceCost getShippingServiceCost() {
        return ShippingServiceCost;
    }
 
    public void setShippingServiceCost(ShippingServiceCost ShippingServiceCost) {
        this.ShippingServiceCost = ShippingServiceCost;
    }

  
}