package kyle.leis.eo.operation.predictwaybill.ebay.vo.response;
 
/**
 * Generated by FreeMarker
 *
 */
public class ShippingAddress  
{
    /********** attribute ***********/
    private String Name;

    private String Street1;

    private String Street2;

    private String CityName;

    private String StateOrProvince;
    
    private String Country;

    private String CountryName;

    private String Phone;

    private String PostalCode;

  
    /********** get/set ***********/
    public String getName() {
        return Name;
    }
 
    public void setName(String Name) {
        this.Name = Name;
    }

    public String getStreet1() {
        return Street1;
    }
 
    public void setStreet1(String Street1) {
        this.Street1 = Street1;
    }

    public String getStreet2() {
        return Street2;
    }
 
    public void setStreet2(String Street2) {
        this.Street2 = Street2;
    }

    public String getCityName() {
        return CityName;
    }
 
    public void setCityName(String CityName) {
        this.CityName = CityName;
    }

    public String getStateOrProvince() {
        return StateOrProvince;
    }
 
    public void setStateOrProvince(String StateOrProvince) {
        this.StateOrProvince = StateOrProvince;
    }

    public String getCountryName() {
        return CountryName;
    }
 
    public void setCountryName(String CountryName) {
        this.CountryName = CountryName;
    }

    public String getPhone() {
        return Phone;
    }
 
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    public String getPostalCode() {
        return PostalCode;
    }
 
    public void setPostalCode(String PostalCode) {
        this.PostalCode = PostalCode;
    }

	public String getCountry() {
		return Country;
	}

	public void setCountry(String country) {
		Country = country;
	}

  
}