package kyle.leis.eo.operation.predictwaybill.ebay.vo.response;
 
/**
 * Generated by FreeMarker
 *
 */
public class Transaction  
{
    /********** attribute ***********/
    private Buyer Buyer;

    private Item Item;

    private int QuantityPurchased;

    private String TransactionID;

    private TransactionPrice TransactionPrice;
    
    private Variation Variation;

  
    /********** get/set ***********/
    public Buyer getBuyer() {
        return Buyer;
    }
 
    public void setBuyer(Buyer Buyer) {
        this.Buyer = Buyer;
    }

    public Item getItem() {
        return Item;
    }
 
    public void setItem(Item Item) {
        this.Item = Item;
    }

    public int getQuantityPurchased() {
        return QuantityPurchased;
    }
 
    public void setQuantityPurchased(int QuantityPurchased) {
        this.QuantityPurchased = QuantityPurchased;
    }

    public String getTransactionID() {
        return TransactionID;
    }
 
    public void setTransactionID(String TransactionID) {
        this.TransactionID = TransactionID;
    }

    public TransactionPrice getTransactionPrice() {
        return TransactionPrice;
    }
 
    public void setTransactionPrice(TransactionPrice TransactionPrice) {
        this.TransactionPrice = TransactionPrice;
    }

	public Variation getVariation() {
		return Variation;
	}

	public void setVariation(Variation variation) {
		Variation = variation;
	}
  
}