package kyle.leis.eo.operation.housewaybill.dax;

import kyle.leis.eo.operation.housewaybill.da.WaybillforauditQuery;

public class WaybillforauditQueryEX extends WaybillforauditQuery {
	public WaybillforauditQueryEX(String startAdddate, String endAdddate, 
			String startFeeCreatedate, String endFeeCreatedate){
		m_strSelectClause = "SELECT cw.cw_code,cw.cw_customerewbcode,cw.cw_ewbcode,cw.cw_serverewbcode,co.co_code,co.co_labelcode,co.co_sname,cw.cw_grossweight,cw.cw_pieces,  cw.cw_chargeweight,cw.cw_serverchargeweight,pk.pk_code,pk.pk_sname,pm.pm_code,pm.pm_name,ct.ct_code,ct.ct_name,odt.dt_code,odt.dt_hubcode,sdt.dt_code,  sdt.dt_hubcode,ddt.dt_code,ddt.dt_hubcode,cddt.dt_code,cddt.dt_hubcode,bw.bw_labelcode,bw.add_date,dbw.bw_labelcode,dbw.add_date,cws.cws_code,cws.cws_name,  " +
				"(select nvl(sum(round(rv.rv_currencyrate * rv.rv_actualtotal, 2)),0) from t_bl_receivable rv where rv.cw_code = cw.cw_code and rv.fs_code != 'E' and ((rv.rv_createdate >= to_date('" + startFeeCreatedate + "', 'yyyy-mm-dd hh24:mi:ss') and to_date('" + endFeeCreatedate + "', 'yyyy-mm-dd hh24:mi:ss') >= rv.rv_createdate) or (rv.rv_createdate >= to_date('" + startAdddate + "', 'yyyy-mm-dd hh24:mi:ss') and to_date('" + endAdddate + "', 'yyyy-mm-dd hh24:mi:ss') >= rv.rv_createdate))) as rvtotal, " +
				"(select nvl(sum(round(py.py_currencyrate * py.py_actualtotal, 2)), 0) from t_bl_payable py where py.cw_code = cw.cw_code and py.bk_code = 'A0201' and py.fs_code != 'E' and ((py.py_createdate >= to_date('" + startFeeCreatedate + "', 'yyyy-mm-dd hh24:mi:ss') and to_date('" + endFeeCreatedate + "', 'yyyy-mm-dd hh24:mi:ss') >= py.py_createdate) or (py.py_createdate >= to_date('" + startAdddate + "', 'yyyy-mm-dd hh24:mi:ss') and to_date('" + endAdddate + "', 'yyyy-mm-dd hh24:mi:ss') >= py.py_createdate))) as pytotal," +
				"fus.fas_code,fus.fas_name,fun_get_reconciliation(cw.cw_code) as reconciliationsign,cw.znv_Name,(select nvl(sum(round(py.py_currencyrate * py.py_actualtotal, 2)), 0) from t_bl_payable py where py.cw_code = cw.cw_code and py.bk_code = 'A0202' and py.fs_code != 'E') as pyrvtotal,sop.op_id,sop.op_name, ee.ee_code,ee.ee_sname FROM t_op_corewaybill cw,t_op_batchwaybill bw,t_op_batchwaybill dbw,t_co_corporation co,t_co_customer cm,t_di_productkind pk,t_di_district odt,t_di_district ddt,t_di_district cddt,t_di_district sdt,t_di_paymentmode pm,t_di_cargotype ct,t_di_corewaybillstatus cws,t_di_financeauditstatus fus,t_di_operator sop, t_di_enterpriseelement ee";
		m_astrConditionWords = new String[] { "cw.cw_customerewbcode in (~~)", "cw.cw_ewbcode in (~~)", "cw.cw_serverewbcode in (~~)", "bw.bw_labelcode = '~~'", "dbw.bw_labelcode = '~~'", "cws.cws_code in (~~)", "pm.pm_code = '~~'", "pk.pk_code = '~~'", "ct.ct_code = '~~'", "odt.dt_code = '~~'", "ddt.dt_code = '~~'", "cddt.dt_code = '~~'", "fus.fas_code = '~~'", "cw.co_code_customer in (~~)", "bw.add_date >= to_date('~~','yyyy-mm-dd hh24:mi:ss')", "to_date('~~','yyyy-mm-dd hh24:mi:ss') >= bw.add_date", "dbw.add_date >= to_date('~~','yyyy-mm-dd hh24:mi:ss')", "to_date('~~','yyyy-mm-dd hh24:mi:ss') >= dbw.add_date", "(co.CO_CarryoverSign = '~~' OR co.CO_CarryoverDate > cw.cw_createdate)", "(co.CO_CarryoverSign = '~~' AND cw.cw_createdate > co.CO_CarryoverDate)", "exists (select cw.cw_code,rv.fk_code from t_bl_receivable rv where cw.cw_code = rv.cw_code and rv.fk_code in(~~))", "fun_get_grossprofit(cw.cw_code) = '~~'", "('Y' = '~~' AND (cw.cw_chargeweight - cw.cw_serverchargeweight) != 0)", "fun_get_reconciliation(cw.cw_code) = '~~'", "fun_get_reconciliation(cw.cw_code) = '~~'", "cw.chn_code_supplier = '~~'", "cw.znv_Name = '~~'", "~~ >= cw.cw_chargeweight", "cw.cw_chargeweight >= ~~", 
				"exists (select rv.rv_id,cw.cw_code from t_bl_receivable rv where rv.cw_code = cw.cw_code and rv.fs_code in (~~))", "exists (select py.py_id,cw.cw_code from t_bl_payable py where py.cw_code = cw.cw_code and py.bk_code = 'A0201' and py.fs_code in ('B','W') and py.br_id = ~~) ", "cw.co_code_supplier = '~~'", "exists (select cal.cw_code from t_fs_corewaybillauditlog cal where cal.cw_code = cw.cw_code and cal.falt_code = '~~')", "sop.op_id = ~~", 
				"exists ((select rv.rv_id from t_bl_receivable rv where rv.cw_code = cw.cw_code and ((rv.rv_createdate >= to_date('~~', 'yyyy-mm-dd hh24:mi:ss') and to_date('~~', 'yyyy-mm-dd hh24:mi:ss') >= rv.rv_createdate) or (rv.rv_createdate >= to_date('" + startAdddate + "', 'yyyy-mm-dd hh24:mi:ss') and to_date('" + endAdddate + "', 'yyyy-mm-dd hh24:mi:ss') >= rv.rv_createdate))) union ((select py.py_id from t_bl_payable py where py.cw_code = cw.cw_code and py.bk_code = 'A0201' and ((py.py_createdate >= to_date('" + startFeeCreatedate + "', 'yyyy-mm-dd hh24:mi:ss') and to_date('" + endFeeCreatedate + "', 'yyyy-mm-dd hh24:mi:ss') >= py.py_createdate) or (py.py_createdate >= to_date('" + startAdddate + "', 'yyyy-mm-dd hh24:mi:ss') and to_date('" + endAdddate + "', 'yyyy-mm-dd hh24:mi:ss') >= py.py_createdate)))))", "ee.ee_structurecode like '~~%'", "(exists (select rv.rv_id from t_bl_receivable rv where rv.cw_code = cw.cw_code and rv.bk_code = 'A0101' and rv.fs_code != 'E' and rv.fk_code in (~~)) and not exists (select py.py_id from t_bl_payable py where py.cw_code = cw.cw_code and py.bk_code = 'A0201' and py.fs_code != 'E' and py.fk_code in (~~)))", "(not exists (select rv.rv_id from t_bl_receivable rv where rv.cw_code = cw.cw_code and rv.bk_code = 'A0101' and rv.fs_code != 'E' and rv.fk_code in (~~)) and exists (select py.py_id from t_bl_payable py where py.cw_code = cw.cw_code and py.bk_code = 'A0201' and py.fs_code != 'E' and py.fk_code in (~~)))" };
	}
}
