package kyle.leis.eo.operation.housewaybill.dax;

public class WaybillforpredictQueryIMEXCNULL extends WaybillforpredictQueryEX {
	
	public WaybillforpredictQueryIMEXCNULL(){
	    m_strSelectClause = "SELECT cw.cw_code,cw.cw_customerewbcode,cw.cw_serverewbcode,cw.cw_ewbcode,pk.pk_code,pk.pk_sename,cw.dt_code_signin,dt.dt_hubcode,dt.dt_ename,hw.hw_shippercompany,hw.hw_shippername,hw.hw_shipperaddress1,hw.hw_shipperaddress2,hw.hw_shipperaddress3,hw.hw_shippertelephone,hw.hw_shipperpostcode,hw.hw_shipperfax,hw.hw_consigneename,hw.hw_consigneecompany,dt.dt_statecode,hw.hw_consigneecity,hw.hw_consigneeaddress1,hw.hw_consigneeaddress2,hw.hw_consigneeaddress3,hw.hw_consigneetelephone,hw.hw_consigneepostcode,hw.hw_consigneefax,hw.hw_bookingid,hw.hw_transactionid,hw.hw_remark,cw.cw_chargeweight,cw.cw_customerchargeweight,pw.pwb_createdate,cw.cw_pieces,cws.cws_code,cws.cws_name,ihs.ihs_code,ihs.ihs_name,cco.co_code,cco.co_labelcode,sco.co_code as scocode,sco.co_labelcode as scolabelcode,sco.co_sename as scosename,chn.chn_code,chn.chn_sename,chn.chn_sname,chn.chn_customerlabel, FUN_GET_CUSTOMEREWBCODES(cw.cw_code) as originorderid, FUN_GET_SPECIALTYPESIGN(cw.cw_code, 'A0101') as AlonecustomSign,hw.HW_ATTACHEINFOSIGN, chn.CHN_CustomLable,pw.pwb_PrintDate,HW_SignInDate,pw.pwb_DeclareDate,dt.dt_name,pk.pk_showserverewbcode,hw.HW_ConsigneeAddressEX,hw.HW_ConsigneeNameEX,bwb.bw_labelcode,chn.chn_masteraccount ,chn.chn_selflablecode, '' as subconame,ddt.dt_code as cdtcode,ddt.dt_hubcode as cdthubcode, hw.hw_consigneecityex,hw.pat_code,hw.dt_code,hw.cgk_code,hw.bk_code,hw.hw_dutypaidsign FROM T_OP_COREWAYBILL cw,t_OP_PREDICTWAYBILL pw,T_OP_HOUSEWAYBILL hw,T_DI_PRODUCTKIND pk,T_DI_DISTRICT dt,T_DI_COREWAYBILLSTATUS cws,t_co_corporation cco, t_co_corporation sco,t_chn_channel chn, t_di_issueholdstatus ihs,t_op_batchwaybill bwb, T_DI_DISTRICT ddt";
	}

}
