package kyle.leis.ds.report.finance.dax;

import kyle.leis.ds.report.finance.da.FeegroupbycoQuery;

public class BeforeFeegroupbycoQueryEX extends FeegroupbycoQuery {
	public BeforeFeegroupbycoQueryEX(String strStartCreateDate,
			String strEndCreateDate){
		m_strSelectClause = "SELECT co.co_sname,pk.pk_sname,count(1) as billcount,nvl(sum(cw.cw_pieces),0) as sumpieces,nvl(sum(cw.cw_chargeweight),0) as sumchargeweight,nvl(sum(cw.cw_serverchargeweight),0) as sumserverchargeweight,nvl(sum((select sum(round(rv.rv_currencyrate * rv.rv_actualtotal,2)) from t_bl_receivable rv where rv.cw_code = cw.cw_code and rv.bk_code = 'A0101' and rv.rv_createdate >= to_date('" + strStartCreateDate + "', 'yyyy-mm-dd hh24:mi:ss') and to_date('" + strEndCreateDate + "', 'yyyy-mm-dd hh24:mi:ss') >= rv.rv_createdate and rv.fs_code in ('D','C','B','W'))),0) as rvTotal, nvl(sum((select sum(round(py.py_currencyrate * py.py_actualtotal,2)) from t_bl_payable py where py.cw_code = cw.cw_code and py.bk_code = 'A0201' and py.py_createdate >= to_date('" + strStartCreateDate + "', 'yyyy-mm-dd hh24:mi:ss') and to_date('" + strEndCreateDate + "', 'yyyy-mm-dd hh24:mi:ss') >= py.py_createdate and py.fs_code in ('D','C','B','W'))),0) as pyTotal,op.op_name,co.co_labelcode,nvl(sum((select sum(rv.rv_actualtotal) from t_bl_receivable rv where rv.cw_code = cw.cw_code and rv.bk_code = 'A0101' and rv.ck_code = 'RMB' and rv.rv_createdate >= to_date('" + strStartCreateDate + "', 'yyyy-mm-dd hh24:mi:ss') and to_date('" + strEndCreateDate + "', 'yyyy-mm-dd hh24:mi:ss') >= rv.rv_createdate and rv.fs_code in ('D','C','B','W'))),0) as RMBRvTotal,nvl(sum((select sum(rv.rv_actualtotal) from t_bl_receivable rv where rv.cw_code = cw.cw_code and rv.ck_code = 'HKD' and rv.bk_code = 'A0101' and rv.rv_createdate >= to_date('" + strStartCreateDate + "', 'yyyy-mm-dd hh24:mi:ss') and to_date('" + strEndCreateDate + "', 'yyyy-mm-dd hh24:mi:ss') >= rv.rv_createdate and rv.fs_code in ('D','C','B','W'))),0) as HKDRvTotal,ee.ee_sname FROM t_op_corewaybill cw,t_op_batchwaybill bw,t_co_corporation co,t_di_productkind pk, t_co_customer cm,t_di_operator op,t_co_supplier cs,t_chn_channel chn, T_DI_ENTERPRISEELEMENT ee ";
		m_strWhereClause = "cw.co_code_customer = co.co_code and cw.co_code_supplier = cs.co_code(+) and cw.bw_code_arrival = bw.bw_code and cw.pk_code = pk.pk_code and cw.ee_code = ee.ee_code and co.co_code = cm.co_code and cm.cm_op_id_sale = op.op_id and cw.chn_code_supplier = chn.chn_code(+) and cw.cws_code NOT IN ('EL', 'CEL') and ((exists (select rv.rv_id from t_bl_receivable rv where rv.cw_code = cw.cw_code and rv.rv_createdate >= to_date('" + strStartCreateDate + "','yyyy-mm-dd hh24:mi:ss') and to_date('" + strEndCreateDate + "','yyyy-mm-dd hh24:mi:ss') >= rv.rv_createdate)) or (exists (select py.py_id from t_bl_payable py where py.cw_code = cw.cw_code and py.bk_code = 'A0201' and py.py_createdate >= to_date('" + strStartCreateDate + "','yyyy-mm-dd hh24:mi:ss') and to_date('" + strEndCreateDate + "','yyyy-mm-dd hh24:mi:ss') >= py.py_createdate)))";
	}
}
