package kyle.leis.eo.operation.predictwaybill.ebay.vo.request;
 
/**
 * Generated by FreeMarker
 *
 */
public class Pagination  
{
    /********** attribute ***********/
    private int EntriesPerPage;

    private int PageNumber;

  
    /********** get/set ***********/
    public int getEntriesPerPage() {
        return EntriesPerPage;
    }
 
    public void setEntriesPerPage(int EntriesPerPage) {
        this.EntriesPerPage = EntriesPerPage;
    }

    public int getPageNumber() {
        return PageNumber;
    }
 
    public void setPageNumber(int PageNumber) {
        this.PageNumber = PageNumber;
    }

  
}