package kyle.leis.eo.operation.predictwaybill.ebay.vo;
 
/**
 * Generated by FreeMarker
 *
 */
public class Errors  
{
    /********** attribute ***********/
    private String ShortMessage;

    private String LongMessage;

    private String ErrorCode;

    private String SeverityCode;

    private String ErrorClassification;

  
    /********** get/set ***********/
    public String getShortMessage() {
        return ShortMessage;
    }
 
    public void setShortMessage(String ShortMessage) {
        this.ShortMessage = ShortMessage;
    }

    public String getLongMessage() {
        return LongMessage;
    }
 
    public void setLongMessage(String LongMessage) {
        this.LongMessage = LongMessage;
    }

    public String getErrorCode() {
        return ErrorCode;
    }
 
    public void setErrorCode(String ErrorCode) {
        this.ErrorCode = ErrorCode;
    }

    public String getSeverityCode() {
        return SeverityCode;
    }
 
    public void setSeverityCode(String SeverityCode) {
        this.SeverityCode = SeverityCode;
    }

    public String getErrorClassification() {
        return ErrorClassification;
    }
 
    public void setErrorClassification(String ErrorClassification) {
        this.ErrorClassification = ErrorClassification;
    }

  
}